import { NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: Request) {
  console.log("=== BACKEND: /api/send-email ENDPOINT HIT ===")

  try {
    const body = await req.json()
    const { recipients, emailContent } = body

    if (!recipients || !Array.isArray(recipients) || recipients.length === 0) {
      console.error("BACKEND: No recipients array found")
      return NextResponse.json({ error: "No recipients provided" }, { status: 400 })
    }

    if (!process.env.RESEND_API_KEY) {
      console.error("BACKEND: Missing API Key")
      return NextResponse.json({ error: "Missing Resend API Key" }, { status: 500 })
    }

    // 🔥 HACKATHON DEMO MODE: Only grab the very first person from the CSV
    const targetRecipient = recipients[0]
    
    console.log("BACKEND: Extracted Target Recipient:", targetRecipient)

    // Handle potential CSV capitalization issues (e.g., 'Email' instead of 'email')
    const targetEmail = targetRecipient.email || targetRecipient.Email || targetRecipient.EMAIL
    const targetName = targetRecipient.name || targetRecipient.Name || targetRecipient.NAME || "there"

    if (!targetEmail) {
      console.error("BACKEND: targetRecipient.email is undefined! Check CSV column headers.")
      return NextResponse.json({ 
        error: "First recipient has no 'email' property. Ensure your CSV has an email column." 
      }, { status: 400 })
    }

    console.log(`BACKEND: Attempting to send Resend email to: ${targetEmail}`)

    // Send a single email instead of a batch
    const { data, error } = await resend.emails.send({
      
      // ✅ CORRECTED: Using Resend's testing domain so it doesn't get blocked
      from: "AI Event Agent <onboarding@resend.dev>", 
      
      // ✅ REMINDER: This target recipient MUST be the exact email address you used to sign up for Resend
      to: [targetEmail], 
      
      subject: "Hackathon Demo: AI Event Outreach", 
      
      html: `
        <div style="font-family: sans-serif; color: #333; line-height: 1.6;">
          <p>Hi ${targetName},</p>
          
          <div style="margin-top: 20px; margin-bottom: 20px; padding: 15px; background-color: #f8fafc; border-left: 4px solid #10b981;">
            <em>This email was dynamically generated by the Mailing Agent.</em><br/><br/>
            ${emailContent ? emailContent.replace(/\n/g, "<br />") : "No AI content generated."} 
          </div>
          
          <p>Best regards,</p>
          <p><strong>Your Hackathon Team</strong></p>
        </div>
      `,
    })

    if (error) {
      console.error("=== BACKEND: RESEND API ERROR ===", error)
      return NextResponse.json({ error: error.message }, { status: 400 })
    }

    console.log("=== BACKEND: EMAIL SENT SUCCESSFULLY ===", data)
    return NextResponse.json({ success: true, data, demoEmailSentTo: targetEmail })

  } catch (error: any) {
    console.error("=== BACKEND: INTERNAL SERVER ERROR ===", error)
    return NextResponse.json({ error: error.message || "Failed to send email" }, { status: 500 })
  }
}